### ISSUE TITLE
爆笑随机 值为0时依然能随机成功

### ISSUE THREAD

**Issue by BryanSer** [MoonDrinkWind/MoonGems#1]
https://github.com/MoonDrinkWind/MoonGems/blob/97e9fa5ad0643c484e718f0e46ad8abbe0713dbf/src/main/java/moon/atbar/egems/utils/GemTools.java#L48

**Comment by MoonDrinkWind** [comment]
感谢反馈，我们很快将修复这个问题。

**Comment by BryanSer** [comment]
朋友 还没修复的问题不能close的

**Comment by MoonDrinkWind** [comment]
emmmm
